#!/usr/bin/env bash

HOME_DIRECTORY="/Users/${USER}"
DOTFILES_DIRECTORY="$HOME_DIRECTORY/.dotfiles"

# Link all of the symlink files into the root.
for f in *.symlink
do
  ln -s "$DOTFILES_DIRECTORY/$f" "$HOME_DIRECTORY/.`basename $f .symlink`"
done

# Do all the Homebrew installations.
brew bundle install --file=Brewfile
