name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  installer:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run installer
      run: ./install.sh --dry-run --force-dotfiles --skip packages,mise-shell-activate,user,tools
