name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: macos-latest 
    steps:
    - uses: actions/checkout@v4
    - name: Cleanup existing files
      run: rm -rf ~/.gitconfig
    - name: Run installer
      run: ./install.sh
