name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: macos-latest 
    steps:
    - uses: actions/checkout@v4
    - name: Run installer
      shell: /usr/bin/fish {0}
      run: ./install.sh
