name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: macos-latest 
    defaults:
      run:
        shell: fish
    steps:
    - uses: actions/checkout@v4
    - name: Run installer
      run: ./install.sh
